"""initial_schema

Revision ID: 8db5f0998fbf
Revises:
Create Date: 2026-07-14 12:51:51.367092
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8db5f0998fbf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.String(length=255), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(op.f("ix_audit_events_actor"), "audit_events", ["actor"], unique=False)
    op.create_index(
        op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False
    )
    op.create_index(
        "ix_audit_target_created",
        "audit_events",
        ["target_type", "target_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("principal_id", sa.String(length=255), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("principal_id", "idempotency_key", name="uq_idempotency_principal_key"),
    )
    op.create_index(
        op.f("ix_idempotency_records_principal_id"),
        "idempotency_records",
        ["principal_id"],
        unique=False,
    )
    op.create_table(
        "installation_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("principal_id", sa.String(length=255), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("agent", sa.String(length=64), nullable=False),
        sa.Column("namespace", sa.String(length=63), nullable=False),
        sa.Column("skill_name", sa.String(length=63), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("remote_sha256", sa.String(length=64), nullable=False),
        sa.Column("local_sha256", sa.String(length=64), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("conflict_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('installed', 'local_changes', 'conflict', 'rolled_back', 'removed')",
            name="ck_installation_reports_state",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_installation_reports_client_id"),
        "installation_reports",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_installation_reports_principal_id"),
        "installation_reports",
        ["principal_id"],
        unique=False,
    )
    op.create_table(
        "namespaces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column("owner_org", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_namespaces_slug"), "namespaces", ["slug"], unique=True)
    op.create_table(
        "worker_heartbeats",
        sa.Column("worker_id", sa.String(length=64), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("worker_id"),
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("namespace_id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("tags_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("visibility IN ('private', 'public')", name="ck_skills_visibility"),
        sa.ForeignKeyConstraint(["namespace_id"], ["namespaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace_id", "slug", name="uq_skills_namespace_slug"),
    )
    op.create_index(op.f("ix_skills_owner_id"), "skills", ["owner_id"], unique=False)
    op.create_index(op.f("ix_skills_slug"), "skills", ["slug"], unique=False)
    op.create_index(op.f("ix_skills_visibility"), "skills", ["visibility"], unique=False)
    op.create_index(
        "ix_skills_visibility_owner", "skills", ["visibility", "owner_id"], unique=False
    )
    op.create_table(
        "upload_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("skill_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("quarantine_key", sa.String(length=1024), nullable=False),
        sa.Column("expected_sha256", sa.String(length=64), nullable=True),
        sa.Column("actual_sha256", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("declared_license", sa.String(length=128), nullable=False),
        sa.Column("signature_key_id", sa.String(length=255), nullable=True),
        sa.Column("signature_base64", sa.Text(), nullable=True),
        sa.Column("compatibility_json", sa.JSON(), nullable=False),
        sa.Column("error_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('created', 'uploaded', 'finalized', 'scanned', 'rejected')",
            name="ck_upload_sessions_status",
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quarantine_key"),
        sa.UniqueConstraint("skill_id", "version", name="uq_upload_sessions_skill_version"),
    )
    op.create_index(
        op.f("ix_upload_sessions_skill_id"), "upload_sessions", ["skill_id"], unique=False
    )
    op.create_index(op.f("ix_upload_sessions_status"), "upload_sessions", ["status"], unique=False)
    op.create_table(
        "skill_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("skill_id", sa.String(length=36), nullable=False),
        sa.Column("upload_id", sa.String(length=36), nullable=True),
        sa.Column("semver", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("artifact_key", sa.String(length=1024), nullable=True),
        sa.Column("manifest_key", sa.String(length=1024), nullable=True),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=True),
        sa.Column("manifest_json", sa.JSON(), nullable=True),
        sa.Column("scan_status", sa.String(length=32), nullable=False),
        sa.Column("signature_status", sa.String(length=32), nullable=False),
        sa.Column("scan_attempts", sa.Integer(), nullable=False),
        sa.Column("scan_lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("immutable", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deprecated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "scan_status IN ('pending', 'failed', 'passed', 'passed_with_warnings')",
            name="ck_skill_versions_scan_status",
        ),
        sa.CheckConstraint(
            "signature_status IN ('not_checked', 'pending', 'verified', "
            "'not_required', 'required_missing')",
            name="ck_skill_versions_signature_status",
        ),
        sa.CheckConstraint(
            "status IN ('pending_scan', 'scanning', 'scan_failed', 'draft', 'submitted', "
            "'approved', 'rejected', 'published', 'deprecated')",
            name="ck_skill_versions_status",
        ),
        sa.CheckConstraint(
            "manifest_sha256 IS NULL OR length(manifest_sha256) = 64",
            name="ck_skill_versions_manifest_sha256",
        ),
        sa.CheckConstraint(
            "sha256 IS NULL OR length(sha256) = 64", name="ck_skill_versions_sha256"
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["upload_id"], ["upload_sessions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "skill_id", name="uq_skill_versions_id_skill"),
        sa.UniqueConstraint("skill_id", "semver", name="uq_skill_versions_skill_semver"),
        sa.UniqueConstraint("upload_id"),
    )
    op.create_index(
        op.f("ix_skill_versions_manifest_sha256"),
        "skill_versions",
        ["manifest_sha256"],
        unique=False,
    )
    op.create_index(op.f("ix_skill_versions_sha256"), "skill_versions", ["sha256"], unique=False)
    op.create_index(
        op.f("ix_skill_versions_skill_id"), "skill_versions", ["skill_id"], unique=False
    )
    op.create_index(
        "ix_skill_versions_skill_status", "skill_versions", ["skill_id", "status"], unique=False
    )
    op.create_index(op.f("ix_skill_versions_status"), "skill_versions", ["status"], unique=False)
    op.create_table(
        "external_publications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("authorized_by", sa.String(length=255), nullable=False),
        sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("destination_owner", sa.String(length=255), nullable=False),
        sa.Column("destination_repository", sa.String(length=255), nullable=False),
        sa.Column("tag_name", sa.String(length=255), nullable=False),
        sa.Column("policy_version", sa.String(length=32), nullable=False),
        sa.Column("published_url", sa.Text(), nullable=True),
        sa.Column("external_release_id", sa.String(length=255), nullable=True),
        sa.Column("evidence_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('requested', 'authorized', 'publishing', 'published', "
            "'failed_policy', 'failed_manual_review')",
            name="ck_external_publications_status",
        ),
        sa.ForeignKeyConstraint(["version_id"], ["skill_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id", "provider", name="uq_publication_version_provider"),
    )
    op.create_index(
        op.f("ix_external_publications_version_id"),
        "external_publications",
        ["version_id"],
        unique=False,
    )
    op.create_table(
        "labels",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("skill_id", sa.String(length=36), nullable=False),
        sa.Column("label", sa.String(length=63), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("etag", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skills.id"], name="fk_labels_skill", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["version_id", "skill_id"],
            ["skill_versions.id", "skill_versions.skill_id"],
            name="fk_labels_version_same_skill",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("skill_id", "label", name="uq_labels_skill_label"),
    )
    op.create_index(op.f("ix_labels_skill_id"), "labels", ["skill_id"], unique=False)
    op.create_table(
        "registry_changes",
        sa.Column("sequence", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("skill_id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("compatibility_index", sa.Text(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('version.published', 'version.deprecated', "
            "'label.moved', 'label.removed')",
            name="ck_registry_changes_event_type",
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["version_id"], ["skill_versions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("sequence"),
    )
    op.create_index(
        op.f("ix_registry_changes_compatibility_index"),
        "registry_changes",
        ["compatibility_index"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registry_changes_created_at"), "registry_changes", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_registry_changes_event_type"), "registry_changes", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_registry_changes_skill_id"), "registry_changes", ["skill_id"], unique=False
    )
    op.create_index(
        op.f("ix_registry_changes_version_id"), "registry_changes", ["version_id"], unique=False
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("reviewer", sa.String(length=255), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("signature_status", sa.String(length=32), nullable=False),
        sa.Column("evidence_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("decision IN ('approved', 'rejected')", name="ck_reviews_decision"),
        sa.ForeignKeyConstraint(["version_id"], ["skill_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reviews_version_id"), "reviews", ["version_id"], unique=False)
    op.create_table(
        "skill_files",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=True),
        sa.ForeignKeyConstraint(["version_id"], ["skill_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id", "path", name="uq_skill_files_version_path"),
    )
    op.create_index(op.f("ix_skill_files_version_id"), "skill_files", ["version_id"], unique=False)
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE FUNCTION skillhub_guard_skill_version() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
              IF TG_OP = 'DELETE' THEN
                IF OLD.immutable THEN
                  RAISE EXCEPTION 'immutable Skill version cannot be deleted';
                END IF;
                RETURN OLD;
              END IF;
              IF OLD.immutable THEN
                IF NEW.immutable IS DISTINCT FROM TRUE
                   OR NEW.skill_id IS DISTINCT FROM OLD.skill_id
                   OR NEW.upload_id IS DISTINCT FROM OLD.upload_id
                   OR NEW.semver IS DISTINCT FROM OLD.semver
                   OR NEW.sha256 IS DISTINCT FROM OLD.sha256
                   OR NEW.artifact_key IS DISTINCT FROM OLD.artifact_key
                   OR NEW.manifest_key IS DISTINCT FROM OLD.manifest_key
                   OR NEW.manifest_sha256 IS DISTINCT FROM OLD.manifest_sha256
                   OR NEW.manifest_json IS DISTINCT FROM OLD.manifest_json
                   OR NEW.scan_status IS DISTINCT FROM OLD.scan_status
                   OR NEW.signature_status IS DISTINCT FROM OLD.signature_status THEN
                  RAISE EXCEPTION 'immutable Skill version payload cannot be changed';
                END IF;
                IF NEW.status IS DISTINCT FROM OLD.status AND NOT (
                     (OLD.status = 'submitted' AND NEW.status IN ('approved', 'rejected'))
                  OR (OLD.status = 'approved' AND NEW.status = 'published')
                  OR (OLD.status = 'published' AND NEW.status = 'deprecated')
                ) THEN
                  RAISE EXCEPTION 'invalid immutable Skill lifecycle transition';
                END IF;
              END IF;
              RETURN NEW;
            END;
            $$;

            CREATE TRIGGER skillhub_skill_version_worm
            BEFORE UPDATE OR DELETE ON skill_versions
            FOR EACH ROW EXECUTE FUNCTION skillhub_guard_skill_version();

            CREATE FUNCTION skillhub_reject_evidence_mutation() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
              RAISE EXCEPTION 'append-only evidence cannot be updated or deleted';
            END;
            $$;

            CREATE TRIGGER skillhub_audit_append_only
            BEFORE UPDATE OR DELETE ON audit_events
            FOR EACH ROW EXECUTE FUNCTION skillhub_reject_evidence_mutation();

            CREATE TRIGGER skillhub_reviews_append_only
            BEFORE UPDATE OR DELETE ON reviews
            FOR EACH ROW EXECUTE FUNCTION skillhub_reject_evidence_mutation();

            CREATE TRIGGER skillhub_changes_append_only
            BEFORE UPDATE OR DELETE ON registry_changes
            FOR EACH ROW EXECUTE FUNCTION skillhub_reject_evidence_mutation();
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP FUNCTION IF EXISTS skillhub_reject_evidence_mutation() CASCADE")
        op.execute("DROP FUNCTION IF EXISTS skillhub_guard_skill_version() CASCADE")
    op.drop_index(op.f("ix_skill_files_version_id"), table_name="skill_files")
    op.drop_table("skill_files")
    op.drop_index(op.f("ix_reviews_version_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_registry_changes_version_id"), table_name="registry_changes")
    op.drop_index(op.f("ix_registry_changes_skill_id"), table_name="registry_changes")
    op.drop_index(op.f("ix_registry_changes_event_type"), table_name="registry_changes")
    op.drop_index(op.f("ix_registry_changes_created_at"), table_name="registry_changes")
    op.drop_index(op.f("ix_registry_changes_compatibility_index"), table_name="registry_changes")
    op.drop_table("registry_changes")
    op.drop_index(op.f("ix_labels_skill_id"), table_name="labels")
    op.drop_table("labels")
    op.drop_index(op.f("ix_external_publications_version_id"), table_name="external_publications")
    op.drop_table("external_publications")
    op.drop_index(op.f("ix_skill_versions_status"), table_name="skill_versions")
    op.drop_index("ix_skill_versions_skill_status", table_name="skill_versions")
    op.drop_index(op.f("ix_skill_versions_skill_id"), table_name="skill_versions")
    op.drop_index(op.f("ix_skill_versions_sha256"), table_name="skill_versions")
    op.drop_index(op.f("ix_skill_versions_manifest_sha256"), table_name="skill_versions")
    op.drop_table("skill_versions")
    op.drop_index(op.f("ix_upload_sessions_status"), table_name="upload_sessions")
    op.drop_index(op.f("ix_upload_sessions_skill_id"), table_name="upload_sessions")
    op.drop_table("upload_sessions")
    op.drop_index("ix_skills_visibility_owner", table_name="skills")
    op.drop_index(op.f("ix_skills_visibility"), table_name="skills")
    op.drop_index(op.f("ix_skills_slug"), table_name="skills")
    op.drop_index(op.f("ix_skills_owner_id"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(op.f("ix_namespaces_slug"), table_name="namespaces")
    op.drop_table("namespaces")
    op.drop_table("worker_heartbeats")
    op.drop_index(op.f("ix_installation_reports_principal_id"), table_name="installation_reports")
    op.drop_index(op.f("ix_installation_reports_client_id"), table_name="installation_reports")
    op.drop_table("installation_reports")
    op.drop_index(op.f("ix_idempotency_records_principal_id"), table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index("ix_audit_target_created", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
