const state={baseUrl:location.origin,token:sessionStorage.getItem("skillhub.token")||"",skills:[],selected:null};
const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const esc=(v)=>String(v??"").replace(/[&<>'"]/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
let toastTimer;
function toast(message){const node=$("#toast");node.textContent=message;node.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove("show"),2800)}
function apiUrl(path){return new URL(path,state.baseUrl).toString()}
async function api(path,options={}){const headers=new Headers(options.headers||{});if(state.token)headers.set("Authorization",`Bearer ${state.token}`);if(options.json){headers.set("Content-Type","application/json");options.body=JSON.stringify(options.json)}const response=await fetch(apiUrl(path),{...options,headers});if(response.status===304)return{response,data:null};const type=response.headers.get("content-type")||"";const data=type.includes("json")?await response.json():await response.text();if(!response.ok){if(response.status===401)showLogin();throw new Error(data?.detail||`HTTP ${response.status}`)}return{response,data}}
function showLogin(){ $("#login-screen").classList.remove("hidden") }
function hideLogin(){ $("#login-screen").classList.add("hidden") }
async function login(event){event.preventDefault();const error=$("#login-error");error.textContent="";state.baseUrl=$("#login-url").value.replace(/\/$/,"");state.token=$("#login-token").value;try{const{data}=await api("/api/v1/me");sessionStorage.setItem("skillhub.token",state.token);$("#identity-name").textContent=data.subject;hideLogin();await Promise.all([loadSkills(),loadCapabilities(),checkHealth()])}catch(e){state.token="";error.textContent=e.message}}
async function checkHealth(){const chip=$("#health-chip");try{const response=await fetch(apiUrl("/health/ready"));if(!response.ok)throw new Error();chip.className="health-chip ok";chip.querySelector("span").textContent="Registry API 已就绪"}catch{chip.className="health-chip bad";chip.querySelector("span").textContent="服务尚未就绪"}}
async function loadCapabilities(){try{const{data}=await api("/api/v1/system/capabilities");$("#metric-signature").textContent=data.require_signature?"强制":"可选";$("#metric-region").textContent=data.deployment_region==="ap-shanghai"?"上海":data.deployment_region}catch(e){toast(e.message)}}
function formatDate(value){if(!value)return"—";return new Intl.DateTimeFormat("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Shanghai"}).format(new Date(value))}
function renderSkills(){const body=$("#skill-table");body.textContent="";for(const skill of state.skills){const labels=Object.entries(skill.labels||{}).map(([k,v])=>`<span class="label-tag">${esc(k)} · ${esc(v)}</span>`).join("")||"<span class='muted'>尚无</span>";const row=document.createElement("tr");row.className="skill-row";row.innerHTML=`<td><div class="skill-name"><span class="skill-icon">${esc(skill.name[0]?.toUpperCase()||"S")}</span><div><b>${esc(skill.name)}</b><small>${esc(skill.namespace)} · ${esc(skill.description)}</small></div></div></td><td><span class="visibility ${esc(skill.visibility)}">${esc(skill.visibility)}</span></td><td>${labels}</td><td>${esc(formatDate(skill.updated_at))}</td><td class="chevron">›</td>`;row.addEventListener("click",()=>openDetail(skill.namespace,skill.name));body.append(row)}$("#empty-state").classList.toggle("hidden",state.skills.length>0);$("#result-count").textContent=`${state.skills.length} 项`;$("#metric-skills").textContent=state.skills.length;populateSkillSelect()}
async function loadSkills(){try{const q=$("#search-input").value.trim();const{data}=await api(`/api/v1/skills?limit=200${q?`&q=${encodeURIComponent(q)}`:""}`);state.skills=data.items||[];renderSkills();let releases=0;await Promise.all(state.skills.slice(0,20).map(async(s)=>{try{const{data:d}=await api(`/api/v1/skills/${encodeURIComponent(s.namespace)}/${encodeURIComponent(s.name)}`);releases+=d.versions.filter(v=>v.status==="published").length}catch{}}));$("#metric-releases").textContent=releases}catch(e){toast(e.message)}}
function populateSkillSelect(){const select=$("#upload-skill");select.textContent="";for(const s of state.skills){const o=document.createElement("option");o.value=s.id;o.textContent=`${s.namespace}/${s.name}`;select.append(o)}}
function statusClass(status){return["published","approved"].includes(status)?"formal":["scan_failed","rejected","deprecated"].includes(status)?"preview":"cloud"}
async function openDetail(namespace,name){try{const{data}=await api(`/api/v1/skills/${encodeURIComponent(namespace)}/${encodeURIComponent(name)}`);state.selected=data;$("#detail-namespace").textContent=data.namespace.toUpperCase();$("#detail-name").textContent=data.name;$("#detail-description").textContent=data.description;$("#detail-meta").innerHTML=`<span class="visibility ${esc(data.visibility)}">${esc(data.visibility)}</span>${(data.tags||[]).map(t=>`<span class="label-tag">${esc(t)}</span>`).join("")}`;renderVersions(data);$("#detail-drawer").classList.add("open");$("#drawer-backdrop").classList.add("open");$("#detail-drawer").setAttribute("aria-hidden","false")}catch(e){toast(e.message)}}
function actionButton(label,action,version,kind="ghost"){const b=document.createElement("button");b.className=`button ${kind}`;b.textContent=label;b.addEventListener("click",()=>versionAction(action,version));return b}
function renderVersions(skill){const list=$("#version-list");list.textContent="";if(!skill.versions.length){list.innerHTML="<p class='muted'>尚无版本。请从发布中心上传 ZIP 包。</p>";return}for(const v of skill.versions){const card=document.createElement("article");card.className="version-card";card.innerHTML=`<header><b>v${esc(v.version)}</b><span class="status ${statusClass(v.status)}">${esc(v.status)}</span></header><small>扫描：${esc(v.scan_status)} · 签名：${esc(v.signature_status)} · ${esc(formatDate(v.created_at))}</small>`;const actions=document.createElement("div");actions.className="version-actions";if(v.status==="draft")actions.append(actionButton("提交审核","submit",v));if(v.status==="submitted")actions.append(actionButton("审核通过","approve",v,"primary"));if(v.status==="approved")actions.append(actionButton("发布 stable","publish",v,"primary"));if(v.status==="published"){actions.append(actionButton("授权 GitHub","github",v));actions.append(actionButton("弃用","deprecate",v,"danger"))}card.append(actions);list.append(card)}}
async function versionAction(action,version){const map={submit:[`/api/v1/versions/${version.id}:submit`,{}],approve:[`/api/v1/versions/${version.id}:approve`,{decision:"approved",evidence:{source:"personal-console"}}],publish:[`/api/v1/versions/${version.id}:publish`,{label:"stable"}],deprecate:[`/api/v1/versions/${version.id}:deprecate`,{}],github:[`/api/v1/versions/${version.id}/github-authorization`,{confirmation:"PUBLISH_PUBLICLY",license_confirmed:true,sensitive_content_reviewed:true}]};if(action==="github"&&!confirm("确认将此精确版本公开发布到 GitHub？该授权不可自动扩展到其他版本。"))return;if(action==="deprecate"&&!confirm("确认弃用该版本并移除指向它的标签？"))return;try{const[path,json]=map[action];await api(path,{method:"POST",json});toast("操作已提交");await openDetail(state.selected.namespace,state.selected.name);await loadSkills()}catch(e){toast(e.message)}}
function closeDrawer(){ $("#detail-drawer").classList.remove("open");$("#drawer-backdrop").classList.remove("open");$("#detail-drawer").setAttribute("aria-hidden","true") }
async function createSkill(event){event.preventDefault();const form=event.currentTarget;const fd=new FormData(form);try{await api("/api/v1/skills",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},json:{namespace:fd.get("namespace"),name:fd.get("name"),description:fd.get("description"),visibility:fd.get("visibility"),tags:String(fd.get("tags")||"").split(",").map(v=>v.trim()).filter(Boolean)}});$("#create-dialog").close();form.reset();toast("技能已创建");await loadSkills()}catch(e){toast(e.message)}}
async function uploadVersion(event){event.preventDefault();const form=event.currentTarget;const fd=new FormData(form);const file=fd.get("archive");const compatibility=String(fd.get("compatibility")||"").split(",").map(v=>v.trim()).filter(Boolean);const signatureKey=String(fd.get("signature_key_id")||"").trim();const signature=String(fd.get("signature_base64")||"").trim();try{const{data:session}=await api(`/api/v1/skills/${encodeURIComponent(fd.get("skill_id"))}/uploads`,{method:"POST",json:{version:fd.get("version"),license:fd.get("license"),compatibility,signature_key_id:signatureKey||null,signature_base64:signature||null}});await api(session.upload_url,{method:"PUT",headers:{"Content-Type":"application/zip"},body:file});const{data:version}=await api(`/api/v1/uploads/${session.id}:finalize`,{method:"POST"});$("#upload-dialog").close();form.reset();toast(`v${version.version} 已进入安全扫描`);await loadSkills()}catch(e){toast(e.message)}}
function switchView(view){$$('[data-view]').forEach(n=>n.classList.toggle("active",n.dataset.view===view));$$('.view').forEach(n=>n.classList.toggle("active",n.id===`${view}-view`));const names={registry:"技能仓库",publishing:"发布中心",integrations:"Agent 集成",settings:"系统设置"};$("#view-title").textContent=names[view];$("#search-input").closest("label").classList.toggle("hidden",view!=="registry");$("#create-button").classList.toggle("hidden",view!=="registry")}
const integrations=[['Codex','正式本地适配','formal','~/.codex/skills'],['Claude Code','正式本地适配','formal','~/.claude/skills'],['TRAE CN','正式本地适配','formal','~/.trae-cn/skills'],['OpenClaw','正式本地适配','formal','CLI / 本地目录'],['Hermes Agent','正式本地适配','formal','~/.hermes/skills'],['WorkBuddy','Preview 引导导入','preview','生成 ZIP 与导入指引'],['飞书 Aily','云端连接器','cloud','list / get / start / drift']];
function renderIntegrations(){const grid=$("#integration-grid");for(const[name,label,status,detail]of integrations){const card=document.createElement("article");card.className="integration-card";card.innerHTML=`<header><span class="integration-logo">${esc(name[0])}</span><span class="status ${status}">${esc(label)}</span></header><h3>${esc(name)}</h3><p>${esc(detail)}</p>`;grid.append(card)}}
function bind(){$("#login-form").addEventListener("submit",login);$("#create-form").addEventListener("submit",createSkill);$("#upload-form").addEventListener("submit",uploadVersion);$("#create-button").addEventListener("click",()=>$("#create-dialog").showModal());$("#upload-button").addEventListener("click",()=>{$("#upload-dialog").showModal()});$("#refresh-button").addEventListener("click",loadSkills);$("#close-drawer").addEventListener("click",closeDrawer);$("#drawer-backdrop").addEventListener("click",closeDrawer);$$('.close-dialog').forEach(b=>b.addEventListener("click",()=>b.closest("dialog").close()));$$('[data-view]').forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view)));let timer;$("#search-input").addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(loadSkills,250)})}
async function boot(){bind();renderIntegrations();$("#login-url").value=location.origin;await checkHealth();if(!state.token){showLogin();return}try{const{data}=await api("/api/v1/me");$("#identity-name").textContent=data.subject;hideLogin();await Promise.all([loadSkills(),loadCapabilities()])}catch{showLogin()}}
boot();
